name: my_web_app 
description: Personal portfolio website built with Flutter Web.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_html: ^3.0.0-beta.2 # لعرض HTML (IFrame) على الويب
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.0 # لعرض IFrame على الويب
  cached_network_image: ^3.3.1
  animate_do: ^3.3.4
  carousel_slider: ^5.0.0
  countup: ^0.1.4
  expandable: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  http: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/